name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build macOS
      run: swift build -v
    - name: Run macOS tests
      run: swift test -v
  
  build-Linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Linux
      run: swift build -v
    - name: Run Linux tests
      run: swift test -v

  build-macOS-self-hosted:

    runs-on: [self-hosted, macOS, x64]

    steps:
    - uses: actions/checkout@v2
    - name: Build on self hosted macOS
      run: swift build -v
    - name: Run tests on self hosted macOS
      run: swift test -v
