name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build macOS
      run: swift build -v
    - name: Run macOS tests
      run: swift test -v
  
  build-Linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build Linux
      run: swift build -v
    - name: Run Linux tests
      run: swift test -v
